# Competition configuration options

options:
  insert_models_over_bins: true
  fill_demo_tray: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    parts:
      part_0:
        type: piston_rod_part
        pose:
          xyz: [0.1, 0, 0]
          rpy: [0, 0, 0]
      part_1:
        type: gear_part
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 'pi']

models_over_bins:
  bin3:
    models:
      gear_part:
        xyz_start: [0.0, 0.0, 0.0]
        xyz_end: [0.3, 0.6, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 5
  bin4:
    models:
      gasket_part:
        xyz_start: [0.0, 0.05, 0.0]
        xyz_end: [0.15, 0.55, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 4
  bin2:
    models:
      piston_rod_part:
        xyz_start: [0.0, 0.05, 0.0]
        xyz_end: [0.15, 0.55, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 4

faulty_parts:
  - piston_rod_part_5  # this part gets spawned manually in the tutorial

time_limit: -1


# Competitor trial configuration options

arm:
  type: ur10

sensors:
  break_beam:
    type: break_beam
    pose:
      xyz: [1.6, 2.25, 0.47]
      rpy: [0, 0, 'pi']
  proximity_sensor:
    type: proximity_sensor
    pose:
      xyz: [0.8, 2.6, 0.47]
      rpy: [0, 0, 0]
  camera_1:
    type: camera
    pose:
      xyz: [0.5, 2.8, 2.4]
      rpy: [0, 0.9, '-pi']
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [0, 0.22, 1.75]
      rpy: [0, 0.9, '-pi']
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [1.2, 2.25, 1.2]
      rpy: ['-pi/2', 'pi/2', '-pi']
  quality_control_sensor_1:
    type: quality_control
    pose:
      xyz: [1.2, 0.25, 1.2]
      rpy: ['-pi/2', 'pi/2', '-pi']
  quality_control_sensor_2:
    type: quality_control
    pose:
      xyz: [1.2, -2.25, 1.2]
      rpy: ['-pi/2', 'pi/2', 'pi']
  laser_profiler:
    type: laser_profiler
    pose:
      xyz: [1.21, 4, 1.18]
      rpy: ['-pi', 'pi/2', 'pi/2']
