arm:
  type: ur10
sensors:
  quality_control_1:
    type: quality_control
    pose:
      xyz: [1.2, 2.25, 1.66]
      rpy: ['-pi/2', 'pi/2', '-pi']
  quality_control_2:
    type: quality_control
    pose:
      xyz: [1.2, 0.25, 1.66]
      rpy: ['-pi/2', 'pi/2', '-pi']
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 2.25, 0.91]
      rpy: [0, 0, 'pi']
  proximity_sensor_1:
    type: proximity_sensor
    pose:
      xyz: [0.8, 2.6, 0.916]
      rpy: [0, 0, 0]
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [-0.66, 0.22, 1.36]
      rpy: ['pi/2', 1.32, 0]
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [0.3, 3.15, 1.5]
      rpy: [0, 'pi/2', 0]
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [0.3, -3.15, 1.5]
      rpy: [0, 'pi/2', 0]
  laser_profiler_1:
    type: laser_profiler
    pose:
      xyz: [1.21, 4, 1.64]
      rpy: ['-pi', 'pi/2', 'pi/2']
