# Competition configuration options

options:
  insert_models_over_bins: true
  fill_demo_shipment: true
  start_box_at_belt_center: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    parts:
      part_0:
        type: piston_rod_part
        pose:
          xyz: [0.1, 0, 0]
          rpy: [0, 0, 0]
      part_1:
        type: gear_part
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 'pi']

models_over_bins:
  bin3:
    models:
      gear_part:
        xyz_start: [0.0, 0.0, 0.0]
        xyz_end: [0.3, 0.37, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 5
  bin4:
    models:
      gasket_part:
        xyz_start: [0.0, 0.05, 0.0]
        xyz_end: [0.2, 0.37, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3
  bin2:
    models:
      piston_rod_part:
        xyz_start: [0.0, 0.0, 0.0]
        xyz_end: [0.25, 0.35, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3

faulty_parts:
  - piston_rod_part_5  # this part gets spawned manually in the tutorial

time_limit: -1
