time_limit: 500

options:
  insert_models_over_bins: true
  fill_demo_shipment: false
  start_box_at_belt_center: false
  model_type_aliases:
    order_part1: piston_rod_part
    order_part2: disk_part
    order_part3: gear_part
  gazebo_state_logging: true
  visualize_drop_regions: false

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    products:
      part_0:
        type: order_part1
        pose:
          xyz: [0.08, -0.1, 0]
          rpy: [0, 0, 'pi']
      part_1:
        type: order_part2
        pose:
          xyz: [-0.1, -0.1, 0]
          rpy: [0, 0, 0.3]
      part_2:
        type: order_part2
        pose:
          xyz: [0.0, 0.15, 0]
          rpy: [0, 0, '-pi/2']
      part_3:
        type: order_part3
        pose:
          xyz: [0.0, -0.15, 0]
          rpy: [0, 0, 'pi']

models_over_bins:
  bin4:
    models:
      piston_rod_part:
        xyz_start: [0.05, 0.15, 0.0]
        xyz_end: [0.2, 0.25, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 1
        num_models_y: 1
  bin2:
    models:
      disk_part:
        xyz_start: [0.1, 0.05, 0.0]
        xyz_end: [0.25, 0.35, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 1
        num_models_y: 2
  bin3:
    models:
      gear_part:
        xyz_start: [0.1, 0.0, 0.0]
        xyz_end: [0.3, 0.37, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 1
        num_models_y: 1

drops:
  drop_regions:
    bin4_unreachable:
      min:
        xyz: [-0.5, 1.55, 0.7]
      max:
        xyz: [-0.4, 2.40, 1.3]
      destination:
        xyz: [-0.4, 1.8, 0.76]
        rpy: [0, 0, 0.2]
      product_type_to_drop: piston_rod_part
    bin3_unreachable:
      min:
        xyz: [-0.5, 0.7, 0.7]
      max:
        xyz: [-0.4, 1.60, 1.3]
      destination:
        xyz: [-0.4, 1.12, 0.76]
        rpy: [0, 0, 0.4]
      product_type_to_drop: gear_part

faulty_products:
  - disk_part_48

random_seed: 7
