time_limit: 500

options:
  fill_demo_shipment: false
  insert_models_over_bins: true
  spawn_extra_models: false
  model_type_aliases:
    order_part1: piston_rod_part
    order_part2: gear_part
    order_part3: disk_part
  gazebo_state_logging: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    products:
      product_0:
        type: order_part1
        pose:
          xyz: [0.05, -0.2, 0]
          rpy: [0, 0, 0]
      product_1:
        type: order_part2
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 0]
      product_2:
        type: order_part1
        pose:
          xyz: [0.15, 0.1, 0]
          rpy: [0, 0, 0]
      product_3:
        type: order_part2
        pose:
          xyz: [-0.15, 0.1, 0]
          rpy: [0, 0, 0]
      product_4:
        type: order_part3
        pose:
          xyz: [0.0, 0.1, 0]
          rpy: [0, 0, 0]
  order_1:
    announcement_condition: wanted_products
    announcement_condition_value: 3
    shipment_count: 1
    products:
      product_0:
        type: order_part2
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 0]
      product_1:
        type: order_part2
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 0]
      product_2:
        type: order_part3
        pose:
          xyz: [0.1, 0.15, 0]
          rpy: [0, 0, 0]
      product_3:
        type: order_part2
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin3:
    models:
      gear_part:
        xyz_start: [0.05, 0.15, 0.0]
        xyz_end: [0.2, 0.37, 0.0]
        rpy: [0, 0, 'pi/2']
        num_models_x: 2
        num_models_y: 3
  bin2:
    models:
      disk_part:
        xyz_start: [0.0, 0.05, 0.0]
        xyz_end: [0.2, 0.37, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3
  bin5:
    models:
      piston_rod_part:
        xyz_start: [0.0, 0.0, 0.0]
        xyz_end: [0.25, 0.35, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 3
  bin1:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.25, 0.3, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 1
        num_models_y: 2

random_seed: 12

faulty_products:
  - piston_rod_part_77
  - gear_part_126
  - gear_part_110
  - piston_rod_part_0
  - piston_rod_part_148
