options:
  insert_models_over_bins: true
  fill_demo_shipment: false
  start_box_at_belt_center: false
  gazebo_state_logging: true
  visualize_drop_regions: false

time_limit: 500

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    products:
      part_0:
        type: piston_rod_part
        pose:
          xyz: [0, 0.1, 0]
          rpy: [0, 0, '-pi/2']
      part_1:
        type: gasket_part
        pose:
          xyz: [0.06, 0.18, 0]
          rpy: [0, 0, 0]
      part_3:
        type: gasket_part
        pose:
          xyz: [0.08, -0.15, 0]
          rpy: [0, 0, 0]
      part_4:
        type: piston_rod_part
        pose:
          xyz: [-0.08, -0.15, 0]
          rpy: [0, 0, 0]
  order_0_update_0:
    announcement_condition: unwanted_products
    announcement_condition_value: 2
    shipment_count: 1
    products:
      part_0:
        type: gear_part
        pose:
          xyz: [0.1, -0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: gear_part
        pose:
          xyz: [0.1, 0.15, 0]
          rpy: [0, 0, 'pi/4']
      part_2:
        type: disk_part
        pose:
          xyz: [-0.1, -0.15, 0]
          rpy: [0, 0, 'pi/2']

models_over_bins:
  bin2:
    models:
      gasket_part:
        xyz_start: [0.05, 0.1, 0.0]
        xyz_end: [0.25, 0.27, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 1
        num_models_y: 2
  bin5:
    models:
      disk_part:
        xyz_start: [0.0, 0.13, 0.0]
        xyz_end: [0.27, 0.27, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 1
  bin1:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.15, 0.0]
        xyz_end: [0.25, 0.3, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2
  bin3:
    models:
      gear_part:
        xyz_start: [0.0, 0.0, 0.0]
        xyz_end: [0.3, 0.37, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 5

sensor_blackout:
  product_count: 2
  duration: 40

drops:
  drop_regions:
    bin3_reachable_left:
      min:
        xyz: [-0.85, 0.7, 0.7]
      max:
        xyz: [-0.65, 1.10, 1.3]
      destination:
        xyz: [-0.65, 0.95, 0.8]
        rpy: ['pi', 0, 0.5]
      product_type_to_drop: gear_part
    bin3_reachable_right:
      min:
        xyz: [-0.85, 1.10, 0.7]
      max:
        xyz: [-0.65, 1.60, 1.3]
      destination:
        xyz: [-0.65, 1.4, 0.8]
        rpy: ['pi', 0, 0.5]
      product_type_to_drop: gear_part
    bin5_reachable:
      min:
        xyz: [-0.85, 2.3, 0.7]
      max:
        xyz: [-0.78, 3.2, 1.3]
      destination:
        xyz: [-0.8, 2.75, 0.85]
        rpy: ['pi', 0, 0.5]
      product_type_to_drop: disk_part

faulty_products:
  - disk_part_63

random_seed: 10

