options:
  insert_models_over_bins: true
  fill_demo_shipment: false
  start_box_at_belt_center: false
  gazebo_state_logging: true

time_limit: 500

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    products:
      part_0:
        type: piston_rod_part
        pose:
          xyz: [0, 0.1, 0]
          rpy: [0, 0, '-pi/2']
      part_1:
        type: piston_rod_part
        pose:
          xyz: [0.04, 0.18, 0]
          rpy: [0, 0, 'pi/2']
      part_3:
        type: gear_part
        pose:
          xyz: [0.08, -0.15, 0]
          rpy: [0, 0, 0]
      part_4:
        type: gear_part
        pose:
          xyz: [-0.08, -0.15, 0]
          rpy: [0, 0, 0]
  order_0_update_0:
    announcement_condition: unwanted_products
    announcement_condition_value: 2
    shipment_count: 1
    products:
      part_0:
        type: disk_part
        pose:
          xyz: [0.1, -0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: pulley_part
        pose:
          xyz: [0.1, 0.15, 0]
          rpy: ['pi', 0, 0]
      part_2:
        type: gasket_part
        pose:
          xyz: [-0.1, -0.15, 0]
          rpy: [0, 0, 'pi/2']

models_over_bins:
  bin1:
    models:
      gear_part:
        xyz_start: [0.12, 0.02, 0.0]
        xyz_end: [0.27, 0.24, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 3
  bin3:
    models:
      gasket_part:
        xyz_start: [0.05, 0.1, 0.0]
        xyz_end: [0.25, 0.27, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 1
        num_models_y: 2
  bin2:
    models:
      disk_part:
        xyz_start: [0.1, 0.13, 0.0]
        xyz_end: [0.27, 0.27, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 1
  bin5:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.15, 0.0]
        xyz_end: [0.25, 0.3, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2
  bin4:
    models:
      pulley_part:
        xyz_start: [0.15, 0.05, 0.0]
        xyz_end: [0.15, 0.35, 0.0]
        rpy: [0, 0, 'pi/2']
        num_models_x: 1
        num_models_y: 2

sensor_blackout:
  product_count: 2
  duration: 70

drops:
  drop_regions:
    shipping_box_0_impeding_gasket:
      frame: shipping_box_0::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [-0.1, 0.05, 0.12]
        rpy: [0, 0, -0.2]
      product_type_to_drop: gasket_part
    shipping_box_1_impeding_gasket:
      frame: shipping_box_1::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [-0.1, 0.05, 0.12]
        rpy: [0, 0, -0.2]
      product_type_to_drop: gasket_part
    shipping_box_2_impeding_gasket:
      frame: shipping_box_2::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [-0.1, 0.05, 0.12]
        rpy: [0, 0, -0.2]
      product_type_to_drop: gasket_part
    shipping_box_3_impeding_gasket:
      frame: shipping_box_3::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [-0.1, 0.05, 0.12]
        rpy: [0, 0, -0.2]
      product_type_to_drop: gasket_part
    shipping_box_4_impeding_gasket:
      frame: shipping_box_4::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [-0.1, 0.05, 0.12]
        rpy: [0, 0, -0.2]
      product_type_to_drop: gasket_part
    shipping_box_5_impeding_gasket:
      frame: shipping_box_5::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [-0.1, 0.05, 0.12]
        rpy: [0, 0, -0.2]
      product_type_to_drop: gasket_part
    shipping_box_0_impeding_disk:
      frame: shipping_box_0::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [0.0, 0.15, 0.12]
        rpy: [0, 0, 0.2]
      product_type_to_drop: disk_part
    shipping_box_1_impeding_disk:
      frame: shipping_box_1::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [0.0, 0.15, 0.12]
        rpy: [0, 0, 0.2]
      product_type_to_drop: disk_part
    shipping_box_2_impeding_disk:
      frame: shipping_box_2::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [0.0, 0.15, 0.12]
        rpy: [0, 0, 0.2]
      product_type_to_drop: disk_part
    shipping_box_3_impeding_disk:
      frame: shipping_box_3::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [0.0, 0.15, 0.12]
        rpy: [0, 0, 0.2]
      product_type_to_drop: disk_part
    shipping_box_4_impeding_disk:
      frame: shipping_box_4::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [0.0, 0.15, 0.12]
        rpy: [0, 0, 0.2]
      product_type_to_drop: disk_part
    shipping_box_5_impeding_disk:
      frame: shipping_box_5::box_base
      min:
        xyz: [-0.15, -0.35, 0.0]
      max:
        xyz: [0.15, 0.35, 0.5]
      destination:
        xyz: [0.0, 0.15, 0.12]
        rpy: [0, 0, 0.2]
      product_type_to_drop: disk_part

random_seed: 9
