time_limit: 500

options:
  fill_demo_shipment: false
  insert_models_over_bins: true
  spawn_extra_models: false
  model_type_aliases:
    order_part1: piston_rod_part
    order_part2: gasket_part
    order_part3: gear_part
  gazebo_state_logging: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 2
    products:
      part_0:
        type: order_part1
        pose:
          xyz: [0.2, -0.2, 0]
          rpy: [0, 0, 'pi/2']
      part_1:
        type: order_part1
        pose:
          xyz: [-0.2, -0.2, 0]
          rpy: [0, 0, '-pi/2']
      part_2:
        type: order_part2
        pose:
          xyz: [0.15, -0.05, 0]
          rpy: [0, 0, 0.5]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.15, 0.05, 0]
          rpy: [0, 0, -0.5]
      part_4:
        type: order_part3
        pose:
          xyz: [0.0, 0.15, 0]
          rpy: [0, 0, 'pi']

models_over_bins:
  bin1:
    models:
      gear_part:
        xyz_start: [0.1, 0.0, 0.0]
        xyz_end: [0.3, 0.37, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 4
  bin4:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.35, 0.25, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3
  bin3:
    models:
      gasket_part:
        xyz_start: [0.05, 0.05, 0.0]
        xyz_end: [0.25, 0.35, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 3

random_seed: 1

faulty_products:
  - piston_rod_part_40
  - piston_rod_part_136
  - gasket_part_121
  - gasket_part_33
