options:
  insert_models_over_bins: true
  fill_demo_shipment: false
  start_box_at_belt_center: false
  model_type_aliases:
    order_part1: gear_part
    order_part2: piston_rod_part
    order_part3: gasket_part
    order_part4: disk_part
  gazebo_state_logging: true

time_limit: 500

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    products:
      part_0:
        type: order_part1
        pose:
          xyz: [0.17, -0.15, 0]
          rpy: [0, 0, 'pi/3']
      part_1:
        type: order_part1
        pose:
          xyz: [-0.17, -0.15, 0]
          rpy: [0, 0, 'pi/3']
      part_2:
        type: order_part2
        pose:
          xyz: [0.15, -0.05, 0]
          rpy: [0, 0, 0.5]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.15, -0.05, 0]
          rpy: [0, 0, 0.5]
      part_4:
        type: order_part3
        pose:
          xyz: [0.0, 0.15, 0]
          rpy: [0, 0, 'pi']
  order_1:
    announcement_condition: wanted_products
    announcement_condition_value: 3
    shipment_count: 1
    products:
      part_0:
        type: order_part2
        pose:
          xyz: [0.2, -0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part1
        pose:
          xyz: [0.2, 0.2, 0]
          rpy: [0, 0, 0]
      part_2:
        type: order_part2
        pose:
          xyz: [0, -0.2, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part3
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: [0, 0, ]
      part_4:
        type: order_part3
        pose:
          xyz: [0.0, 0.15, 0]
          rpy: [0, 0, 'pi']

models_over_bins:
  bin1:
    models:
      gear_part:
        xyz_start: [0.12, 0.02, 0.0]
        xyz_end: [0.27, 0.24, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 2
  bin3:
    models:
      gasket_part:
        xyz_start: [0.05, 0.1, 0.0]
        xyz_end: [0.25, 0.27, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2
  bin2:
    models:
      disk_part:
        xyz_start: [0.1, 0.13, 0.0]
        xyz_end: [0.27, 0.27, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 1
        num_models_y: 2
  bin5:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.15, 0.0]
        xyz_end: [0.25, 0.3, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3

sensor_blackout:
  product_count: 3
  duration: 40

random_seed: 14
