time_limit: 500

options:
  insert_models_over_bins: true
  fill_demo_shipment: false
  start_box_at_belt_center: false
  gazebo_state_logging: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 2
    products:
      part_0:
        type: piston_rod_part
        pose:
          xyz: [0.1, -0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: gear_part
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 'pi']
      part_2:
        type: gear_part
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]
  order_0_update_0:
    announcement_condition: wanted_products
    announcement_condition_value: 2
    shipment_count: 2
    products:
      part_0:
        type: disk_part
        pose:
          xyz: [0.1, -0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: gear_part
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 'pi']
      part_2:
        type: gear_part
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: piston_rod_part
        pose:
          xyz: [0.1, 0.15, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin5:
    models:
      gear_part:
        xyz_start: [0.1, 0.05, 0.0]
        xyz_end: [0.3, 0.37, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 3
  bin2:
    models:
      gasket_part:
        xyz_start: [0.05, 0.1, 0.0]
        xyz_end: [0.2, 0.37, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 1
        num_models_y: 2
  bin3:
    models:
      disk_part:
        xyz_start: [0.1, 0.05, 0.0]
        xyz_end: [0.25, 0.35, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 1
        num_models_y: 2
  bin1:
    models:
      piston_rod_part:
        xyz_start: [0.05, 0.1, 0.0]
        xyz_end: [0.25, 0.35, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2

sensor_blackout:
  product_count: 2
  duration: 30

faulty_products:
  - piston_rod_part_18
  - piston_rod_part_58

random_seed: 5
