arm:
  type: ur10
sensors:
  break_beam:
    type: break_beam
    pose:
      xyz: [1.6, 2.25, 0.47]
      rpy: [0, 0, 'pi']
  proximity_sensor:
    type: proximity_sensor
    pose:
      xyz: [0.8, 2.6, 0.47]
      rpy: [0, 0, 0]
  camera_1:
    type: camera
    pose:
      xyz: [0.5, 2.8, 2.4]
      rpy: [0, 0.9, '-pi']
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [0, 0.22, 1.75]
      rpy: [0, 0.9, '-pi']
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [1.2, 2.25, 1.2]
      rpy: ['-pi/2', 'pi/2', '-pi']
  quality_control_sensor_1:
    type: quality_control
    pose:
      xyz: [1.2, 0.25, 1.2]
      rpy: ['-pi/2', 'pi/2', '-pi']
  quality_control_sensor_2:
    type: quality_control
    pose:
      xyz: [1.2, -2.25, 1.2]
      rpy: ['-pi/2', 'pi/2', 'pi']
  laser_profiler:
    type: laser_profiler
    pose:
      xyz: [1.21, 4, 1.18]
      rpy: ['-pi', 'pi/2', 'pi/2']
