sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.663, 3.9, 0.5]
      rpy: [0, 0, 'pi']
  proximity_sensor_1:
    type: proximity_sensor
    pose:
      xyz: [0.73, 2.6, 0.47]
      rpy: [0, 0, 0]
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [-0.4, 2.0, 1.54]
      rpy: [0, 1.2, '-pi']
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [1.2, 2.25, 1.185]
      rpy: ['-pi/2', 'pi/2', '-pi']
  quality_control_sensor_1:
    type: quality_control
    pose:
      xyz: [1.2, 1.0, 1.2]
      rpy: ['-pi/2', 'pi/2', '-pi']
  quality_control_sensor_2:
    type: quality_control
    pose:
      xyz: [1.2, -0.7, 1.2]
      rpy: ['-pi/2', 'pi/2', 'pi']
  depth_camera_1:
    type: depth_camera
    pose:
      xyz: [-0.64, 2.01, 1.45]
      rpy: [-1.59, 1.17, 'pi']
  laser_profiler_1:
    type: laser_profiler
    pose:
      xyz: [1.21, 3.1, 1.17]
      rpy: ['-pi', 'pi/2', 'pi/2']
